name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC
      run: sudo apt-get install g++

    - name: Build
      run: g++ -o hello main.cpp

    - name: Run
      run: ./hello
